version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 931053721040.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t sample-ida-app .
      - docker tag sample-ida-app:latest 931053721040.dkr.ecr.us-east-1.amazonaws.com/sample-ida-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 931053721040.dkr.ecr.us-east-1.amazonaws.com/sample-ida-app:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes